version: '3.7'

services:
  nitecap:
    build:
      context: .
      dockerfile: Dockerfile
    image: nitecap_img
    ports:
      - 5000:5000
    environment:
      - ENV=${ENV}
      - DATABASE_FILE=${DATABASE_FILE}
      - DATABASE_FOLDER=${DATABASE_FOLDER}
      - SECRET_KEY=${SECRET_KEY}
      - APPLICATION_SETTINGS=${APPLICATION_SETTINGS}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - DB_BACKUP_FOLDER=${DB_BACKUP_FOLDER}
      - DB_BACKUP_LIMIT=${DB_BACKUP_LIMIT}
      - ANNONYMOUS_EMAIL=${ANNONYMOUS_EMAIL}
      - ANNONYMOUS_PWD=${ANNONYMOUS_PWD}
      - SMTP_SERVER_HOST=${SMTP_SERVER_HOST}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - LOG_FILE=${LOG_FILE}
      - LOG_LEVEL=${LOG_LEVEL}
      - SPREADSHEET_BUCKET_NAME=${SPREADSHEET_BUCKET_NAME}
      - COMPUTATION_STATE_MACHINE_ARN=${COMPUTATION_STATE_MACHINE_ARN}
      - NOTIFICATION_API_ENDPOINT=${NOTIFICATION_API_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ./app_data/uploads:${UPLOAD_FOLDER}
      - ./app_data/db:${DATABASE_FOLDER}
      - .:/var/www/flask_apps/nitecap
  smtp:
    image: namshi/smtp
    environment:
      - DISABLE_IPV6=1
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
    ports:
      - 25:25
volumes:
  nitecap_data:
  nitecap_db:
