import os

DEBUG = True
ENV='development'
DATABASE = 'nitecap.db'
SQLALCHEMY_DATABASE_URI = "sqlite:///" + DATABASE
SQLALCHEMY_TRACK_MODIFICATIONS = False
JSONIFY_PRETTYPRINT_REGULAR = False
PROPAGATE_EXCEPTIONS = True
MAX_CONTENT_LENGTH = 40 * 1024 * 1024
SECRET_KEY = os.environ["SECRET_KEY"]